### Basic details
title: Pri2m
author: Adam Keeley
email: 
description: 

### Site build settings
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
 
### License config
license: GNU GPLv3
license_url: https://www.gnu.org/licenses/gpl-3.0.html

### Site content
#logo: https://lida.leeds.ac.uk/wp-content/uploads/2016/04/LIDA-logo.png

callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  highlight:
    title: 
    color: yellow
  note:
    title: Note
    color: purple

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.1"